version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  ignore:
      - dependency-name: "actions/*"
        update-types:
            ["version-update:semver-minor", "version-update:semver-patch"]
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  labels: [ ]
  directory: "/"
  target-branch: "dev"
  schedule:
    interval: "weekly"
    day: "sunday"
  open-pull-requests-limit: 50